### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by therealtmmy** [zt4ff/churchradio#31]
I noticed that the audio attached is not playing. 
Is it just a dummy audio?

**Comment by zt4ff** [comment]
@therealtmmy, I stopped development on this project a while ago. Do you like to hop on it.

I can discuss the plans with you

**Comment by therealtmmy** [comment]
I'll love to. Hint me up.

**Comment by zt4ff** [comment]
@therealtmmy  I am closing this and opening new issues indicating what you can do soon. By then I'd be happy to receive suggestions or advice from you.

**Comment by Funshyaj** [comment]
I have worked on this and the sound plays now..
